"""initial schema

Revision ID: fba5048a7fb1
Revises: 
Create Date: 2026-08-19 00:05:48.880128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba5048a7fb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('fluid_type', sa.String(length=50), nullable=False),
    sa.Column('pressure_threshold_kpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vibration_threshold_mm_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('branding_display_name', sa.String(length=200), nullable=True),
    sa.Column('branding_primary_color', sa.String(length=20), nullable=True),
    sa.Column('branding_logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('bronze_event',
    sa.Column('stream', sa.Enum('SENSOR', 'WEATHER', 'REGIONAL_RISK', name='bronze_stream'), nullable=False),
    sa.Column('source_ref_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_event_stream'), 'bronze_event', ['stream'], unique=False)
    op.create_index(op.f('ix_bronze_event_tenant_id'), 'bronze_event', ['tenant_id'], unique=False)
    op.create_table('model_metric',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('dataset_split', sa.String(length=20), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metric_evaluated_at'), 'model_metric', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_model_metric_model_name'), 'model_metric', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_metric_tenant_id'), 'model_metric', ['tenant_id'], unique=False)
    op.create_table('station',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('commissioned_on', sa.Date(), nullable=True),
    sa.Column('throughput_capacity_m3_per_day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_code'), 'station', ['code'], unique=False)
    op.create_index(op.f('ix_station_tenant_id'), 'station', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANNER', 'TECHNICIAN', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('pump',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('design_life_years', sa.Integer(), nullable=True),
    sa.Column('last_overhaul_date', sa.Date(), nullable=True),
    sa.Column('prior_intervention_count', sa.Integer(), nullable=False),
    sa.Column('rated_flow_m3_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rated_pressure_kpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'STANDBY', 'DECOMMISSIONED', name='pump_status'), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_station_id'), 'pump', ['station_id'], unique=False)
    op.create_index(op.f('ix_pump_tag_number'), 'pump', ['tag_number'], unique=False)
    op.create_index(op.f('ix_pump_tenant_id'), 'pump', ['tenant_id'], unique=False)
    op.create_table('regional_risk_score',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('population_density_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('incident_history_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('land_use_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_risk_score_computed_at'), 'regional_risk_score', ['computed_at'], unique=False)
    op.create_index(op.f('ix_regional_risk_score_station_id'), 'regional_risk_score', ['station_id'], unique=False)
    op.create_index(op.f('ix_regional_risk_score_tenant_id'), 'regional_risk_score', ['tenant_id'], unique=False)
    op.create_table('station_risk_composite',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_risk_composite_station_id'), 'station_risk_composite', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_risk_composite_tenant_id'), 'station_risk_composite', ['tenant_id'], unique=False)
    op.create_table('weather_daily_rollup',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_mean', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation_total_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_max_m_s', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_daily_rollup_station_id'), 'weather_daily_rollup', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_daily_rollup_tenant_id'), 'weather_daily_rollup', ['tenant_id'], unique=False)
    op.create_table('weather_reading',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_m_s', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_reading_recorded_at'), 'weather_reading', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_weather_reading_station_id'), 'weather_reading', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_reading_tenant_id'), 'weather_reading', ['tenant_id'], unique=False)
    op.create_table('alert',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_pump_id'), 'alert', ['pump_id'], unique=False)
    op.create_index(op.f('ix_alert_station_id'), 'alert', ['station_id'], unique=False)
    op.create_index(op.f('ix_alert_tenant_id'), 'alert', ['tenant_id'], unique=False)
    op.create_table('feature_attribution',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('shap_values', sa.JSON(), nullable=False),
    sa.Column('top_component', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_attribution_computed_at'), 'feature_attribution', ['computed_at'], unique=False)
    op.create_index(op.f('ix_feature_attribution_pump_id'), 'feature_attribution', ['pump_id'], unique=False)
    op.create_index(op.f('ix_feature_attribution_tenant_id'), 'feature_attribution', ['tenant_id'], unique=False)
    op.create_table('health_deviation_record',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pressure_residual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('health_deviation_index', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_deviation_record_computed_at'), 'health_deviation_record', ['computed_at'], unique=False)
    op.create_index(op.f('ix_health_deviation_record_pump_id'), 'health_deviation_record', ['pump_id'], unique=False)
    op.create_index(op.f('ix_health_deviation_record_tenant_id'), 'health_deviation_record', ['tenant_id'], unique=False)
    op.create_table('prediction_result',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_class', sa.String(length=50), nullable=True),
    sa.Column('risk_score_7d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_result_computed_at'), 'prediction_result', ['computed_at'], unique=False)
    op.create_index(op.f('ix_prediction_result_pump_id'), 'prediction_result', ['pump_id'], unique=False)
    op.create_index(op.f('ix_prediction_result_tenant_id'), 'prediction_result', ['tenant_id'], unique=False)
    op.create_table('pump_feature_window',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vibration_mean', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vibration_std', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temperature_mean', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_std', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_mean', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pressure_std', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('motor_current_mean', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_feature_window_pump_id'), 'pump_feature_window', ['pump_id'], unique=False)
    op.create_index(op.f('ix_pump_feature_window_tenant_id'), 'pump_feature_window', ['tenant_id'], unique=False)
    op.create_table('rul_estimate',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remaining_useful_life_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_lower_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_upper_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mc_dropout_samples', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rul_estimate_computed_at'), 'rul_estimate', ['computed_at'], unique=False)
    op.create_index(op.f('ix_rul_estimate_pump_id'), 'rul_estimate', ['pump_id'], unique=False)
    op.create_index(op.f('ix_rul_estimate_tenant_id'), 'rul_estimate', ['tenant_id'], unique=False)
    op.create_table('sensor_reading',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vibration_mm_s', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_kpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('motor_current_a', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_reading_pump_id'), 'sensor_reading', ['pump_id'], unique=False)
    op.create_index(op.f('ix_sensor_reading_recorded_at'), 'sensor_reading', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_reading_tenant_id'), 'sensor_reading', ['tenant_id'], unique=False)
    op.create_table('work_order',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='work_order_status'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'ALERT', 'SCHEDULE', name='work_order_source'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_pump_id'), 'work_order', ['pump_id'], unique=False)
    op.create_index(op.f('ix_work_order_station_id'), 'work_order', ['station_id'], unique=False)
    op.create_index(op.f('ix_work_order_tenant_id'), 'work_order', ['tenant_id'], unique=False)
    op.create_table('scheduled_maintenance',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='schedule_status'), nullable=False),
    sa.Column('created_from', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_maintenance_pump_id'), 'scheduled_maintenance', ['pump_id'], unique=False)
    op.create_index(op.f('ix_scheduled_maintenance_station_id'), 'scheduled_maintenance', ['station_id'], unique=False)
    op.create_index(op.f('ix_scheduled_maintenance_tenant_id'), 'scheduled_maintenance', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_maintenance_tenant_id'), table_name='scheduled_maintenance')
    op.drop_index(op.f('ix_scheduled_maintenance_station_id'), table_name='scheduled_maintenance')
    op.drop_index(op.f('ix_scheduled_maintenance_pump_id'), table_name='scheduled_maintenance')
    op.drop_table('scheduled_maintenance')
    op.drop_index(op.f('ix_work_order_tenant_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_station_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_pump_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_sensor_reading_tenant_id'), table_name='sensor_reading')
    op.drop_index(op.f('ix_sensor_reading_recorded_at'), table_name='sensor_reading')
    op.drop_index(op.f('ix_sensor_reading_pump_id'), table_name='sensor_reading')
    op.drop_table('sensor_reading')
    op.drop_index(op.f('ix_rul_estimate_tenant_id'), table_name='rul_estimate')
    op.drop_index(op.f('ix_rul_estimate_pump_id'), table_name='rul_estimate')
    op.drop_index(op.f('ix_rul_estimate_computed_at'), table_name='rul_estimate')
    op.drop_table('rul_estimate')
    op.drop_index(op.f('ix_pump_feature_window_tenant_id'), table_name='pump_feature_window')
    op.drop_index(op.f('ix_pump_feature_window_pump_id'), table_name='pump_feature_window')
    op.drop_table('pump_feature_window')
    op.drop_index(op.f('ix_prediction_result_tenant_id'), table_name='prediction_result')
    op.drop_index(op.f('ix_prediction_result_pump_id'), table_name='prediction_result')
    op.drop_index(op.f('ix_prediction_result_computed_at'), table_name='prediction_result')
    op.drop_table('prediction_result')
    op.drop_index(op.f('ix_health_deviation_record_tenant_id'), table_name='health_deviation_record')
    op.drop_index(op.f('ix_health_deviation_record_pump_id'), table_name='health_deviation_record')
    op.drop_index(op.f('ix_health_deviation_record_computed_at'), table_name='health_deviation_record')
    op.drop_table('health_deviation_record')
    op.drop_index(op.f('ix_feature_attribution_tenant_id'), table_name='feature_attribution')
    op.drop_index(op.f('ix_feature_attribution_pump_id'), table_name='feature_attribution')
    op.drop_index(op.f('ix_feature_attribution_computed_at'), table_name='feature_attribution')
    op.drop_table('feature_attribution')
    op.drop_index(op.f('ix_alert_tenant_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_station_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_pump_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_weather_reading_tenant_id'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_station_id'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_recorded_at'), table_name='weather_reading')
    op.drop_table('weather_reading')
    op.drop_index(op.f('ix_weather_daily_rollup_tenant_id'), table_name='weather_daily_rollup')
    op.drop_index(op.f('ix_weather_daily_rollup_station_id'), table_name='weather_daily_rollup')
    op.drop_table('weather_daily_rollup')
    op.drop_index(op.f('ix_station_risk_composite_tenant_id'), table_name='station_risk_composite')
    op.drop_index(op.f('ix_station_risk_composite_station_id'), table_name='station_risk_composite')
    op.drop_table('station_risk_composite')
    op.drop_index(op.f('ix_regional_risk_score_tenant_id'), table_name='regional_risk_score')
    op.drop_index(op.f('ix_regional_risk_score_station_id'), table_name='regional_risk_score')
    op.drop_index(op.f('ix_regional_risk_score_computed_at'), table_name='regional_risk_score')
    op.drop_table('regional_risk_score')
    op.drop_index(op.f('ix_pump_tenant_id'), table_name='pump')
    op.drop_index(op.f('ix_pump_tag_number'), table_name='pump')
    op.drop_index(op.f('ix_pump_station_id'), table_name='pump')
    op.drop_table('pump')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_station_tenant_id'), table_name='station')
    op.drop_index(op.f('ix_station_code'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_model_metric_tenant_id'), table_name='model_metric')
    op.drop_index(op.f('ix_model_metric_model_name'), table_name='model_metric')
    op.drop_index(op.f('ix_model_metric_evaluated_at'), table_name='model_metric')
    op.drop_table('model_metric')
    op.drop_index(op.f('ix_bronze_event_tenant_id'), table_name='bronze_event')
    op.drop_index(op.f('ix_bronze_event_stream'), table_name='bronze_event')
    op.drop_table('bronze_event')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
